[[DataBridgeKnotOptions]]
== DataBridgeKnotOptions

++++
 Describes Service Knot configuration
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[address]]`address`|`String`|
+++
Sets the EB address of the verticle. Default is 'knotx.knot.databridge'
+++
|[[dataDefinitions]]`dataDefinitions`|`Array of link:cheatsheets.adoc#DataSourceDefinition[DataSourceDefinition]`|
+++
Sets the mapping between service aliases and service adapters that will serve the data.
+++
|[[deliveryOptions]]`deliveryOptions`|`link:cheatsheets.adoc#DeliveryOptions[DeliveryOptions]`|
+++
Sets the Vert.x EventBusDeliveryOptions for a given verticle
+++
|===
[[DataSourceDefinition]]
== DataSourceDefinition

++++
 Describes a physical details of HTTP service endpoint the ServiceAdapter will use.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[adapter]]`adapter`|`String`|
+++
Sets the EB adapter of the service adapter
+++
|[[cacheKey]]`cacheKey`|`String`|
+++
Set the cache key
+++
|[[name]]`name`|`String`|
+++
Set the name of the service the will be used on html snippet level.
+++
|[[params]]`params`|`Json object`|
+++
Set the service parameters to be consumed by the adapter.
+++
|===
